citas_admin/blueprints/autoridades/views.py
"""
Autoridades, vistas
"""

import json

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from citas_admin.blueprints.autoridades.forms import AutoridadForm
from citas_admin.blueprints.autoridades.models import Autoridad
from citas_admin.blueprints.bitacoras.models import Bitacora
from citas_admin.blueprints.distritos.models import Distrito
from citas_admin.blueprints.modulos.models import Modulo
from citas_admin.blueprints.permisos.models import Permiso
from citas_admin.blueprints.usuarios.decorators import permission_required
from lib.datatables import get_datatable_parameters, output_datatable_json
from lib.safe_string import safe_clave, safe_message, safe_string

MODULO = "AUTORIDADES"

autoridades = Blueprint("autoridades", __name__, template_folder="templates")


@autoridades.before_request
@login_required
@permission_required(MODULO, Permiso.VER)
def before_request():
    """Permiso por defecto"""


@autoridades.route("/autoridades/datatable_json", methods=["GET", "POST"])
def datatable_json():
    """DataTable JSON para listado de Autoridades"""
    # Tomar parámetros de Datatables
    draw, start, rows_per_page = get_datatable_parameters()
    # Consultar
    consulta = Autoridad.query
    # Primero filtrar por columnas propias
    if "estatus" in request.form:
        consulta = consulta.filter(Autoridad.estatus == request.form["estatus"])
    else:
        consulta = consulta.filter(Autoridad.estatus == "A")
    if "distrito_id" in request.form:
        try:
            distrito_id = int(request.form["distrito_id"])
            consulta = consulta.filter(Autoridad.distrito_id == distrito_id)
        except ValueError:
            pass
    if "materia_id" in request.form:
        try:
            materia_id = int(request.form["materia_id"])
            consulta = consulta.filter(Autoridad.materia_id == materia_id)
        except ValueError:
            pass
    if "clave" in request.form:
        try:
            clave = safe_clave(request.form["clave"])
            if clave != "":
                consulta = consulta.filter(Autoridad.clave.contains(clave))
        except ValueError:
            pass
    if "descripcion" in request.form:
        descripcion = safe_string(request.form["descripcion"], save_enie=True)
        if descripcion != "":
            consulta = consulta.filter(Autoridad.descripcion.contains(descripcion))
    # Luego filtrar por columnas de otras tablas
    if "distrito_nombre" in request.form:
        distrito_nombre = safe_string(request.form["distrito_nombre"], save_enie=True)
        if distrito_nombre != "":
            consulta = consulta.join(Distrito).filter(Distrito.nombre.contains(distrito_nombre))
    # Ordenar y paginar
    registros = consulta.order_by(Autoridad.clave).offset(start).limit(rows_per_page).all()
    total = consulta.count()
    # Elaborar datos para DataTable
    data = []
    for resultado in registros:
        data.append(
            {
                "detalle": {
                    "clave": resultado.clave,
                    "url": url_for("autoridades.detail", autoridad_id=resultado.id),
                },
                "descripcion_corta": resultado.descripcion_corta,
                "distrito_clave": resultado.distrito.clave,
                "distrito_nombre_corto": resultado.distrito.nombre_corto,
            }
        )
    # Entregar JSON
    return output_datatable_json(draw, total, data)


@autoridades.route("/autoridades")
def list_active():
    """Listado de Autoridades activas"""
    return render_template(
        "autoridades/list.jinja2",
        filtros=json.dumps({"estatus": "A"}),
        titulo="Autoridades",
        estatus="A",
    )


@autoridades.route("/autoridades/inactivos")
@permission_required(MODULO, Permiso.ADMINISTRAR)
def list_inactive():
    """Listado de Autoridades inactivas"""
    return render_template(
        "autoridades/list.jinja2",
        filtros=json.dumps({"estatus": "B"}),
        titulo="Autoridades inactivas",
        estatus="B",
    )


@autoridades.route("/autoridades/<int:autoridad_id>")
def detail(autoridad_id):
    """Detalle de una Autoridad"""
    autoridad = Autoridad.query.get_or_404(autoridad_id)
    return render_template("autoridades/detail.jinja2", autoridad=autoridad)


@autoridades.route("/autoridades/nuevo", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.CREAR)
def new():
    """Nueva Autoridad"""
    form = AutoridadForm()
    if form.validate_on_submit():
        # Validar que la clave no se repita
        clave = safe_clave(form.clave.data)
        if Autoridad.query.filter_by(clave=clave).first():
            flash("La clave ya está en uso. Debe de ser única.", "warning")
            return render_template("autoridades/new.jinja2", form=form)
        # Guardar
        autoridad = Autoridad(
            distrito_id=form.distrito.data,
            materia_id=form.materia.data,
            clave=clave,
            descripcion=safe_string(form.descripcion.data, save_enie=True),
            descripcion_corta=safe_string(form.descripcion_corta.data, save_enie=True),
            es_jurisdiccional=form.es_jurisdiccional.data,
            es_notaria=form.es_notaria.data,
            es_organo_especializado=form.es_organo_especializado.data,
            organo_jurisdiccional=form.organo_jurisdiccional.data,
        )
        autoridad.save()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Nueva Autoridad {autoridad.clave}"),
            url=url_for("autoridades.detail", autoridad_id=autoridad.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
        return redirect(bitacora.url)
    return render_template("autoridades/new.jinja2", form=form)


@autoridades.route("/autoridades/edicion/<int:autoridad_id>", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.MODIFICAR)
def edit(autoridad_id):
    """Editar Autoridad"""
    autoridad = Autoridad.query.get_or_404(autoridad_id)
    form = AutoridadForm()
    if form.validate_on_submit():
        es_valido = True
        # Si cambia la clave verificar que no este en uso
        clave = safe_clave(form.clave.data)
        if autoridad.clave != clave:
            autoridad_existente = Autoridad.query.filter_by(clave=clave).first()
            if autoridad_existente and autoridad_existente.id != autoridad_id:
                es_valido = False
                flash("La clave ya está en uso. Debe de ser única.", "warning")
        # Si es valido actualizar
        if es_valido:
            autoridad.distrito_id = form.distrito.data
            autoridad.materia_id = form.materia.data
            autoridad.clave = clave
            autoridad.descripcion = safe_string(form.descripcion.data, save_enie=True)
            autoridad.descripcion_corta = safe_string(form.descripcion_corta.data, save_enie=True)
            autoridad.es_jurisdiccional = form.es_jurisdiccional.data
            autoridad.es_notaria = form.es_notaria.data
            autoridad.es_organo_especializado = form.es_organo_especializado.data
            autoridad.organo_jurisdiccional = form.organo_jurisdiccional.data
            autoridad.save()
            bitacora = Bitacora(
                modulo=Modulo.query.filter_by(nombre=MODULO).first(),
                usuario=current_user,
                descripcion=safe_message(f"Editada Autoridad {autoridad.clave}"),
                url=url_for("autoridades.detail", autoridad_id=autoridad.id),
            )
            bitacora.save()
            flash(bitacora.descripcion, "success")
            return redirect(bitacora.url)
    form.distrito.data = autoridad.distrito_id  # Usa id porque es un SelectField
    form.materia.data = autoridad.materia_id  # Usa id porque es un SelectField
    form.clave.data = autoridad.clave
    form.descripcion.data = autoridad.descripcion
    form.descripcion_corta.data = autoridad.descripcion_corta
    form.es_jurisdiccional.data = autoridad.es_jurisdiccional
    form.es_notaria.data = autoridad.es_notaria
    form.es_organo_especializado.data = autoridad.es_organo_especializado
    form.organo_jurisdiccional.data = autoridad.organo_jurisdiccional
    return render_template("autoridades/edit.jinja2", form=form, autoridad=autoridad)


@autoridades.route("/autoridades/eliminar/<int:autoridad_id>")
@permission_required(MODULO, Permiso.ADMINISTRAR)
def delete(autoridad_id):
    """Eliminar Autoridad"""
    autoridad = Autoridad.query.get_or_404(autoridad_id)
    if autoridad.estatus == "A":
        autoridad.delete()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Eliminado Autoridad {autoridad.clave}"),
            url=url_for("autoridades.detail", autoridad_id=autoridad.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
    return redirect(url_for("autoridades.detail", autoridad_id=autoridad.id))


@autoridades.route("/autoridades/recuperar/<int:autoridad_id>")
@permission_required(MODULO, Permiso.ADMINISTRAR)
def recover(autoridad_id):
    """Recuperar Autoridad"""
    autoridad = Autoridad.query.get_or_404(autoridad_id)
    if autoridad.estatus == "B":
        autoridad.recover()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Recuperado Autoridad {autoridad.clave}"),
            url=url_for("autoridades.detail", autoridad_id=autoridad.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
    return redirect(url_for("autoridades.detail", autoridad_id=autoridad.id))

citas_admin/blueprints/autoridades/templates/autoridades/detail.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/detail.jinja2' as detail %}
{% import 'macros/modals.jinja2' as modals %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Autoridad {{ autoridad.clave }}{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons('Autoridad ' + autoridad.clave) %}
        {{ topbar.button_previous('Autoridades', url_for('autoridades.list_active')) }}
        {% if current_user.can_edit('AUTORIDADES') %}
            {{ topbar.button_edit('Editar', url_for('autoridades.edit', autoridad_id=autoridad.id)) }}
        {% endif %}
        {% if current_user.can_admin('AUTORIDADES') %}
            {% if autoridad.estatus == 'A' %}{{ topbar.button_delete('Eliminar', url_for('autoridades.delete', autoridad_id=autoridad.id)) }}{% endif %}
            {% if autoridad.estatus == 'B' %}{{ topbar.button_recover('Recuperar', url_for('autoridades.recover', autoridad_id=autoridad.id)) }}{% endif %}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call detail.card(estatus=autoridad.estatus) %}
        <div class="row">
            <div class="col-md-6">
                {# detail.label_value_big('Clave', autoridad.clave) #}
                {% if current_user.can_view("DISTRITOS") %}
                    {{ detail.label_value('Distrito', autoridad.distrito.nombre, url_for('distritos.detail', distrito_id=autoridad.distrito_id)) }}
                {% else %}
                    {{ detail.label_value('Distrito', autoridad.distrito.nombre) }}
                {% endif %}
                {% if current_user.can_view("MATERIAS") %}
                    {{ detail.label_value('Materia', autoridad.materia.nombre, url_for('materias.detail', materia_id=autoridad.materia_id)) }}
                {% else %}
                    {{ detail.label_value('Materia', autoridad.materia.nombre) }}
                {% endif %}
                {{ detail.label_value('Descripción', autoridad.descripcion) }}
                {{ detail.label_value('Descripción corta', autoridad.descripcion_corta) }}
            </div>
            <div class="col-md-6">
                {{ detail.label_value_boolean('Es Jurisdiccional', autoridad.es_jurisdiccional, ignore_is_false=True) }}
                {{ detail.label_value_boolean('Es Notaría', autoridad.es_notaria, ignore_is_false=True) }}
                {{ detail.label_value_boolean('Es Órgano Especializado', autoridad.es_organo_especializado, ignore_is_false=True) }}
            </div>
        </div>
    {% endcall %}
    {% if current_user.can_view('USUARIOS') and autoridad.estatus == 'A' %}
        {% call detail.card('Usuarios') %}
            <!-- Filtros Usuarios -->
            <div class="row">
                <div class="col">
                    <form class="row g-1 mb-3" id="filtradorForm" onsubmit="filtrosDTUsuarios.buscar(); return false;">
                        <div class="col-3">
                            <div class="form-floating">
                                <input id="filtroEMail" type="text" class="form-control" aria-label="email">
                                <label for="filtroEMail">e-mail</label>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-floating">
                                <input id="filtroNombres" type="text" class="form-control" aria-label="Nombres" style="text-transform: uppercase;">
                                <label for="filtroNombres">Nombres</label>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-floating">
                                <input id="filtroApellidoPaterno" type="text" class="form-control" aria-label="Apellido paterno" style="text-transform: uppercase;">
                                <label for="filtroApellidoPaterno">Primer paterno</label>
                            </div>
                        </div>
                        <div class="col-3 text-end">
                            <button title="Buscar" class="btn btn-primary btn-lg" onclick="filtrosDTUsuarios.buscar(); return false;" id="button-buscar"><span class="iconify" data-icon="mdi:magnify"></span></button>
                            <button title="Limpiar" class="btn btn-warning btn-lg" type="reset" onclick="filtrosDTUsuarios.limpiar();" id="button-limpiar"><span class="iconify" data-icon="mdi:broom"></span></button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- Datatable Usuarios -->
            <table id="usuarios_datatable" class="table display nowrap" style="width:100%">
                <thead>
                    <tr>
                        <th>Correo electrónico</th>
                        <th>Nombre completo</th>
                    </tr>
                </thead>
            </table>
        {% endcall %}
    {% endif %}
{% endblock %}

{% block custom_javascript %}
    <!-- Eliminar y recuperar -->
    {% if current_user.can_edit('AUTORIDADES') %}
        {% if autoridad.estatus == 'A' %}{{ modals.custom_javascript_delete('Eliminar', '¿Eliminar a ' + autoridad.clave + '?') }}{% endif %}
        {% if autoridad.estatus == 'B' %}{{ modals.custom_javascript_recover('Recuperar', '¿Recuperar a ' + autoridad.clave + '?') }}{% endif %}
    {% endif %}
    <!-- DataTable -->
    <script src="/static/js/datatables-constructor.js"></script>
    <script src="/static/js/datatables-filtros.js"></script>
    {% if current_user.can_view('USUARIOS') and autoridad.estatus == 'A' %}
        <script>
            // DataTable Usuarios
            const constructorDataTable = new ConfigDataTable( '{{ csrf_token() }}' );
            let configDTUsuarios = constructorDataTable.config();
            configDTUsuarios['ajax']['url'] = '/usuarios/datatable_json';
            configDTUsuarios['ajax']['data'] = { 'estatus': "A", 'autoridad_id': {{ autoridad.id }} };
            configDTUsuarios['columns'] = [
                { data: "detalle" },
                { data: "nombre" }
            ];
            configDTUsuarios['columnDefs'] = [
                {
                    targets: 0, // detalle
                    data: null,
                    render: function(data, type, row, meta) {
                        return '<a href="' + data.url + '">' + data.email + '</a>';
                    }
                },
                {
                    targets: 1, // nombre
                    data: null,
                    render: function(data, type, row, meta) {
                        return (data.length > 48 ? data.substring(0, 48) + '…' : data);
                    }
                }
            ];
            // Filtros Usuarios
            const filtrosDTUsuarios = new FiltrosDataTable('#usuarios_datatable', configDTUsuarios);
            filtrosDTUsuarios.agregarInput('filtroEMail', 'email');
            filtrosDTUsuarios.agregarInput('filtroNombres', 'nombres');
            filtrosDTUsuarios.agregarInput('filtroApellidoPaterno', 'apellido_paterno');
            filtrosDTUsuarios.precargar();
        </script>
    {% endif %}
{% endblock %}

citas_admin/blueprints/autoridades/templates/autoridades/edit.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Editar Autoridad {{ autoridad.clave }}{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Editar Autoridad ' + autoridad.clave) }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% set form_kwargs = {'autoridad_id': autoridad.id} %}
        {% call f.form_tag('autoridades.edit', fid='autoridad_form', **form_kwargs) %}
            <div class="row">
                <div class="col-md-12">
                    {% call f.form_group(form.descripcion) %}{% endcall %}
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    {% call f.form_group(form.descripcion_corta) %}{% endcall %}
                    {% call f.form_group(form.clave) %}{% endcall %}
                    {% call f.form_group(form.distrito) %}{% endcall %}
                    {% call f.form_group(form.materia) %}{% endcall %}
                    {% call f.form_group(form.organo_jurisdiccional) %}{% endcall %}
                </div>
                <div class="col-md-6">
                    {% call f.form_group(form.es_jurisdiccional) %}{% endcall %}
                    {% call f.form_group(form.es_notaria) %}{% endcall %}
                    {% call f.form_group(form.es_organo_especializado) %}{% endcall %}
                </div>
            </div>
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}

citas_admin/blueprints/autoridades/templates/autoridades/list.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/list.jinja2' as list %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}{{ titulo }}{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons(titulo) %}
        {% if current_user.can_view('DISTRITOS') %}
            {{ topbar.button_districts('Distritos', url_for('distritos.list_active')) }}
        {% endif %}
        {% if current_user.can_admin('AUTORIDADES') %}
            {% if estatus == 'A' %}{{ topbar.button_list_inactive('Inactivos', url_for('autoridades.list_inactive')) }}{% endif %}
            {% if estatus == 'B' %}{{ topbar.button_list_active('Activos', url_for('autoridades.list_active')) }}{% endif %}
        {% endif %}
        {% if current_user.can_insert('AUTORIDADES') %}
            {{ topbar.button_new('Nueva Autoridad', url_for('autoridades.new')) }}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call list.card() %}
        <!-- Filtros Autoridades -->
        <div class="row">
            <div class="col">
                <form class="row g-1 mb-3" id="filtradorForm" onsubmit="filtrosAutoridades.buscar(); return false;">
                    <div class="col-2">
                        <div class="form-floating">
                            <input id="filtroAutoridadClave" type="text" class="form-control" aria-label="Clave" style="text-transform: uppercase;">
                            <label for="filtroAutoridadClave">Clave</label>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-floating">
                            <input id="filtroAutoridadDescripcion" type="text" class="form-control" aria-label="Descripcion" style="text-transform: uppercase;">
                            <label for="filtroAutoridadDescripcion">Descripción</label>
                        </div>
                    </div>
                    <div class="col-3">
                        <div class="form-floating">
                            <input id="filtroAutoridadDistritoNombre" type="text" class="form-control" aria-label="Distrito" style="text-transform: uppercase;">
                            <label for="filtroAutoridadDistritoNombre">Distrito</label>
                        </div>
                    </div>
                    <div class="col-3 text-end">
                        <button title="Buscar" class="btn btn-primary btn-lg" onclick="filtrosAutoridades.buscar(); return false;" id="button-buscar"><span class="iconify" data-icon="mdi:magnify"></span></button>
                        <button title="Limpiar" class="btn btn-warning btn-lg" type="reset" onclick="filtrosAutoridades.limpiar();" id="button-limpiar"><span class="iconify" data-icon="mdi:broom"></span></button>
                    </div>
                </form>
            </div>
        </div>
        <!-- Datatable Autoridades -->
        <table id="autoridades_datatable" class="table {% if estatus == 'B'%}table-dark{% endif %} display nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>Clave</th>
                    <th>Descripción corta</th>
                    <th>Distrito</th>
                </tr>
            </thead>
        </table>
    {% endcall %}
{% endblock %}

{% block custom_javascript %}
    <script src="/static/js/datatables-constructor.js"></script>
    <script src="/static/js/datatables-filtros.js"></script>
    <script>
        // DataTable autoridades
        const constructorDataTable = new ConfigDataTable( '{{ csrf_token() }}' );
        let configDTAutoridades = constructorDataTable.config();
        configDTAutoridades['ajax']['url'] = '/autoridades/datatable_json';
        configDTAutoridades['ajax']['data'] = {{ filtros }};
        configDTAutoridades['columns'] = [
            { data: "detalle" },
            { data: "descripcion_corta" },
            { data: "distrito_clave" }
        ];
        configDTAutoridades['columnDefs'] = [
            {
                targets: 0, // detalle
                data: null,
                render: function(data, type, row, meta) {
                    return '<a href="' + data.url + '">' + data.clave + '</a>';
                }
            }
        ];
        // Filtros autoridades
        const filtrosAutoridades = new FiltrosDataTable('#autoridades_datatable', configDTAutoridades);
        filtrosAutoridades.agregarInput('filtroAutoridadClave', 'clave');
        filtrosAutoridades.agregarInput('filtroAutoridadDescripcion', 'descripcion');
        filtrosAutoridades.agregarInput('filtroAutoridadDistritoNombre', 'distrito_nombre');
        filtrosAutoridades.precargar();
    </script>
{% endblock %}

citas_admin/blueprints/autoridades/templates/autoridades/new.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Nueva Autoridad{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Nueva Autoridad') }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% call f.form_tag('autoridades.new', fid='autoridad_form') %}
            <div class="row">
                <div class="col-md-12">
                    {% call f.form_group(form.descripcion) %}{% endcall %}
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    {% call f.form_group(form.descripcion_corta) %}{% endcall %}
                    {% call f.form_group(form.clave) %}{% endcall %}
                    {% call f.form_group(form.distrito) %}{% endcall %}
                    {% call f.form_group(form.materia) %}{% endcall %}
                    {% call f.form_group(form.organo_jurisdiccional) %}{% endcall %}
                </div>
                <div class="col-md-6">
                    {% call f.form_group(form.es_jurisdiccional) %}{% endcall %}
                    {% call f.form_group(form.es_notaria) %}{% endcall %}
                    {% call f.form_group(form.es_organo_especializado) %}{% endcall %}
                </div>
            </div>
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}