citas_admin/blueprints/domicilios/views.py
"""
Domicilios, vistas
"""

import json

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from citas_admin.blueprints.bitacoras.models import Bitacora
from citas_admin.blueprints.domicilios.forms import DomicilioForm
from citas_admin.blueprints.domicilios.models import Domicilio
from citas_admin.blueprints.modulos.models import Modulo
from citas_admin.blueprints.permisos.models import Permiso
from citas_admin.blueprints.usuarios.decorators import permission_required
from lib.datatables import get_datatable_parameters, output_datatable_json
from lib.safe_string import safe_message, safe_string

MODULO = "DOMICILIOS"

domicilios = Blueprint("domicilios", __name__, template_folder="templates")


@domicilios.before_request
@login_required
@permission_required(MODULO, Permiso.VER)
def before_request():
    """Permiso por defecto"""


@domicilios.route("/domicilios/datatable_json", methods=["GET", "POST"])
def datatable_json():
    """DataTable JSON para listado de Domicilios"""
    # Tomar parámetros de Datatables
    draw, start, rows_per_page = get_datatable_parameters()
    # Consultar
    consulta = Domicilio.query
    # Primero filtrar por columnas propias
    if "estatus" in request.form:
        consulta = consulta.filter(Domicilio.estatus == request.form["estatus"])
    else:
        consulta = consulta.filter(Domicilio.estatus == "A")
    if "edificio" in request.form:
        consulta = consulta.filter(Domicilio.edificio.contains(safe_string(request.form["edificio"])))
    if "calle" in request.form:
        consulta = consulta.filter(Domicilio.calle.contains(safe_string(request.form["calle"])))
    if "colonia" in request.form:
        consulta = consulta.filter(Domicilio.colonia.contains(safe_string(request.form["colonia"])))
    # Ordenar y paginar
    registros = consulta.order_by(Domicilio.edificio).offset(start).limit(rows_per_page).all()
    total = consulta.count()
    # Elaborar datos para DataTable
    data = []
    for resultado in registros:
        data.append(
            {
                "detalle": {
                    "edificio": resultado.edificio,
                    "url": url_for("domicilios.detail", domicilio_id=resultado.id),
                },
                "estado": resultado.estado,
                "municipio": resultado.municipio,
                "calle": resultado.calle,
                "num_ext": resultado.num_ext,
                "num_int": resultado.num_int,
                "colonia": resultado.colonia,
                "cp": resultado.cp,
            }
        )
    # Entregar JSON
    return output_datatable_json(draw, total, data)


@domicilios.route("/domicilios")
def list_active():
    """Listado de Domicilios activos"""
    return render_template(
        "domicilios/list.jinja2",
        filtros=json.dumps({"estatus": "A"}),
        titulo="Domicilios",
        estatus="A",
    )


@domicilios.route("/domicilios/inactivos")
@permission_required(MODULO, Permiso.ADMINISTRAR)
def list_inactive():
    """Listado de Domicilios inactivos"""
    return render_template(
        "domicilios/list.jinja2",
        filtros=json.dumps({"estatus": "B"}),
        titulo="Domicilios inactivos",
        estatus="B",
    )


@domicilios.route("/domicilios/<int:domicilio_id>")
def detail(domicilio_id):
    """Detalle de un Domicilio"""
    domicilio = Domicilio.query.get_or_404(domicilio_id)
    return render_template("domicilios/detail.jinja2", domicilio=domicilio)


@domicilios.route("/domicilios/nuevo", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.CREAR)
def new():
    """Nuevo Domicilio"""
    form = DomicilioForm()
    if form.validate_on_submit():
        distrito_id = form.distrito.data
        edificio = safe_string(form.edificio.data, max_len=64, save_enie=True)
        estado = safe_string(form.estado.data, max_len=64, save_enie=True)
        municipio = safe_string(form.municipio.data, max_len=64, save_enie=True)
        calle = safe_string(form.calle.data, max_len=256, save_enie=True)
        num_ext = safe_string(form.num_ext.data, max_len=24, save_enie=True)
        num_int = safe_string(form.num_int.data, max_len=24, save_enie=True)
        colonia = safe_string(form.colonia.data, max_len=256, save_enie=True)
        cp = form.cp.data
        # Validar que el edificio no se repita
        if Domicilio.query.filter_by(edificio=edificio).first():
            flash("Ese edificio ya está en uso. Debe de ser único.", "warning")
            return render_template("autoridades/new.jinja2", form=form)
        # Guardar
        domicilio = Domicilio(
            distrito_id=distrito_id,
            edificio=edificio,
            estado=estado,
            municipio=municipio,
            calle=calle,
            num_ext=num_ext,
            num_int=num_int,
            colonia=colonia,
            cp=cp,
            completo=f"{calle} #{num_ext} {num_int}, {colonia}, {municipio}, {estado}, C.P. {cp}",
        )
        domicilio.save()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Nuevo Domicilio {domicilio.edificio}"),
            url=url_for("domicilios.detail", domicilio_id=domicilio.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
        return redirect(bitacora.url)
    return render_template("domicilios/new.jinja2", form=form)


@domicilios.route("/domicilios/edicion/<int:domicilio_id>", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.MODIFICAR)
def edit(domicilio_id):
    """Editar Domicilio"""
    domicilio = Domicilio.query.get_or_404(domicilio_id)
    form = DomicilioForm()
    if form.validate_on_submit():
        es_valido = True
        # Si cambia el edificio verificar que no este en uso
        edificio = safe_string(form.edificio.data, max_len=64, save_enie=True)
        if domicilio.edificio != edificio:
            domicilio_existente = Domicilio.query.filter_by(edificio=edificio).first()
            if domicilio_existente and domicilio_existente.id != domicilio_id:
                es_valido = False
                flash("El edificio ya está en uso. Debe de ser único.", "warning")
        # Si es valido actualizar
        if es_valido:
            domicilio.distrito_id = form.distrito.data
            domicilio.edificio = safe_string(form.edificio.data, max_len=64, save_enie=True)
            domicilio.estado = safe_string(form.estado.data, max_len=64, save_enie=True)
            domicilio.municipio = safe_string(form.municipio.data, max_len=64, save_enie=True)
            domicilio.calle = safe_string(form.calle.data, max_len=256, save_enie=True)
            domicilio.num_ext = safe_string(form.num_ext.data, max_len=24, save_enie=True)
            domicilio.num_int = safe_string(form.num_int.data, max_len=24, save_enie=True)
            domicilio.colonia = safe_string(form.colonia.data, max_len=256, save_enie=True)
            domicilio.cp = form.cp.data
            domicilio.completo = f"{domicilio.calle} #{domicilio.num_ext} {domicilio.num_int}, {domicilio.colonia}, {domicilio.municipio}, {domicilio.estado}, C.P. {domicilio.cp}"
            domicilio.save()
            bitacora = Bitacora(
                modulo=Modulo.query.filter_by(nombre=MODULO).first(),
                usuario=current_user,
                descripcion=safe_message(f"Editado Domicilio {domicilio.edificio}"),
                url=url_for("domicilios.detail", domicilio_id=domicilio.id),
            )
            bitacora.save()
            flash(bitacora.descripcion, "success")
            return redirect(bitacora.url)
    form.distrito.data = domicilio.distrito_id  # Se manda distrito_id porque es un select
    form.edificio.data = domicilio.edificio
    form.estado.data = domicilio.estado
    form.municipio.data = domicilio.municipio
    form.calle.data = domicilio.calle
    form.num_ext.data = domicilio.num_ext
    form.num_int.data = domicilio.num_int
    form.colonia.data = domicilio.colonia
    form.cp.data = domicilio.cp
    return render_template("domicilios/edit.jinja2", form=form, domicilio=domicilio)


@domicilios.route("/domicilios/eliminar/<int:domicilio_id>")
@permission_required(MODULO, Permiso.ADMINISTRAR)
def delete(domicilio_id):
    """Eliminar Domicilio"""
    domicilio = Domicilio.query.get_or_404(domicilio_id)
    if domicilio.estatus == "A":
        domicilio.delete()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Eliminado Domicilio {domicilio.edificio}"),
            url=url_for("domicilios.detail", instance_id=domicilio.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
    return redirect(url_for("domicilios.detail", domicilio_id=domicilio.id))


@domicilios.route("/domicilios/recuperar/<int:domicilio_id>")
@permission_required(MODULO, Permiso.ADMINISTRAR)
def recover(domicilio_id):
    """Recuperar Domicilio"""
    domicilio = Domicilio.query.get_or_404(domicilio_id)
    if domicilio.estatus == "B":
        domicilio.recover()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Recuperado Domicilio {domicilio.edificio}"),
            url=url_for("domicilios.detail", domicilio_id=domicilio.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
    return redirect(url_for("domicilios.detail", domicilio_id=domicilio.id))

citas_admin/blueprints/domicilios/templates/domicilios/detail.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/detail.jinja2' as detail %}
{% import 'macros/modals.jinja2' as modals %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Domicilio {{ domicilio.edificio }}{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons('Domicilio ' + domicilio.edificio) %}
        {{ topbar.button_previous('Domicilios', url_for('domicilios.list_active')) }}
        {% if current_user.can_edit('DOMICILIOS') %}
            {{ topbar.button_edit('Editar', url_for('domicilios.edit', domicilio_id=domicilio.id)) }}
        {% endif %}
        {% if current_user.can_admin('DOMICILIOS') %}
            {% if domicilio.estatus == 'A' %}{{ topbar.button_delete('Eliminar', url_for('domicilios.delete', domicilio_id=domicilio.id)) }}{% endif %}
            {% if domicilio.estatus == 'B' %}{{ topbar.button_recover('Recuperar', url_for('domicilios.recover', domicilio_id=domicilio.id)) }}{% endif %}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call detail.card(estatus=domicilio.estatus) %}
        {% if current_user.can_view("DISTRITOS") %}
            {{ detail.label_value('Distrito', domicilio.distrito.nombre_corto, url_for('distritos.detail', distrito_id=domicilio.distrito_id)) }}
        {% else %}
            {{ detail.label_value('Distrito', domicilio.distrito.nombre_corto) }}
        {% endif %}
        {{ detail.label_value('Edificio', domicilio.edificio) }}
        {{ detail.label_value('Calle', domicilio.calle) }}
        {{ detail.label_value('No. Exterior', domicilio.num_ext) }}
        {{ detail.label_value('No. Interior', domicilio.num_int) }}
        {{ detail.label_value('Colonia', domicilio.colonia) }}
        {{ detail.label_value('Municipio', domicilio.municipio) }}
        {{ detail.label_value('Estado', domicilio.estado) }}
        {{ detail.label_value('C.P.', domicilio.cp) }}
    {% endcall %}
    {% if current_user.can_view('OFICINAS') %}
        {% call detail.card('Oficinas') %}
            <!-- Filtros Oficinas -->
            <div class="row">
                <div class="col">
                    <form class="row g-1 mb-3" id="filtradorForm" onsubmit="filtrosOficinas.buscar(); return false;">
                        <div class="col-2">
                            <div class="form-floating">
                                <input id="filtroClave" type="text" class="form-control" aria-label="Clave" style="text-transform: uppercase;">
                                <label for="filtroClave">Clave</label>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-floating">
                                <input id="filtroDescripcionCorta" type="text" class="form-control" aria-label="Descripción corta" style="text-transform: uppercase;">
                                <label for="filtroDescripcionCorta">Descripción corta</label>
                            </div>
                        </div>
                        <div class="col-6 text-end">
                            <button title="Buscar" class="btn btn-primary btn-lg" onclick="filtrosOficinas.buscar(); return false;" id="button-buscar"><span class="iconify" data-icon="mdi:magnify"></span></button>
                            <button title="Limpiar" class="btn btn-warning btn-lg" type="reset" onclick="filtrosOficinas.limpiar();" id="button-limpiar"><span class="iconify" data-icon="mdi:broom"></span></button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- DataTable Oficinas -->
            <table id="oficinas_datatable" class="table display nowrap" style="width:100%">
                <thead>
                    <tr>
                        <th>Clave</th>
                        <th>Descripción corta</th>
                        <th>Distrito</th>
                        <th><span title="Es Jurisdiccional">Es J.</span></th>
                    </tr>
                </thead>
            </table>
        {% endcall %}
    {% endif %}
{% endblock %}

{% block custom_javascript %}
    {% if current_user.can_admin('DOMICILIOS') %}
        {% if domicilio.estatus == 'A' %}{{ modals.custom_javascript_delete('Eliminar', '¿Eliminar a ' + domicilio.edificio + '?') }}{% endif %}
        {% if domicilio.estatus == 'B' %}{{ modals.custom_javascript_recover('Recuperar', '¿Recuperar a ' + domicilio.edificio + '?') }}{% endif %}
    {% endif %}
    <!-- Constructor de DataTables -->
    <script src="/static/js/datatables-constructor.js"></script>
    <script src="/static/js/datatables-filtros.js"></script>
    <script>
        const constructorDataTable = new ConfigDataTable( '{{ csrf_token() }}' );
    </script>
    <!-- Oficinas de la Domicilio -->
    {% if current_user.can_view('OFICINAS') %}
        <script>
            // DataTable Oficinas
            let configDTOficinas = constructorDataTable.config();
            configDTOficinas['ajax']['url'] = '/oficinas/datatable_json';
            configDTOficinas['ajax']['data'] = { estatus: "A", domicilio_id: {{ domicilio.id}} };
            configDTOficinas['columns'] = [
                { data: "detalle" },
                { data: "descripcion_corta" },
                { data: "distrito_clave" },
                { data: "es_jurisdiccional" }
            ];
            configDTOficinas['columnDefs'] = [
                {
                    targets: 0, // detalle
                    data: null,
                    render: function(data, type, row, meta) {
                        return '<a href="' + data.url + '">' + data.clave + '</a>';
                    }
                },
                {
                    targets: 1, // descripcion_corta
                    data: null,
                    render: function(data, type, row, meta) {
                        return (data.length > 48 ? data.substring(0, 48) + '…' : data);
                    }
                },
                {
                    targets: 3, // es_jurisdiccional
                    data: null,
                    render: function(data, type, row, meta) {
                        if (data) {
                            return 'SI';
                        }
                        return '';
                    }
                }
            ];
            // Filtros Oficinas
            const filtrosOficinas = new FiltrosDataTable('#oficinas_datatable', configDTOficinas);
            filtrosOficinas.agregarInput('filtroClave', 'clave');
            filtrosOficinas.agregarInput('filtroDescripcionCorta', 'descripcion_corta');
            filtrosOficinas.precargar();
        </script>
    {% endif %}
{% endblock %}

citas_admin/blueprints/domicilios/templates/domicilios/edit.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Editar {{ domicilio.edificio }}{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Editar ' + domicilio.edificio) }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% set form_kwargs = {'domicilio_id': domicilio.id} %}
        {% call f.form_tag('domicilios.edit', fid='domicilio_form', **form_kwargs) %}
            {% call f.form_group(form.distrito) %}{% endcall %}
            {% call f.form_group(form.edificio) %}{% endcall %}
            {% call f.form_group(form.estado) %}{% endcall %}
            {% call f.form_group(form.municipio) %}{% endcall %}
            {% call f.form_group(form.calle) %}{% endcall %}
            {% call f.form_group(form.num_ext) %}{% endcall %}
            {% call f.form_group(form.num_int) %}{% endcall %}
            {% call f.form_group(form.colonia) %}{% endcall %}
            {% call f.form_group(form.cp) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}

citas_admin/blueprints/domicilios/templates/domicilios/list.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/list.jinja2' as list %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}{{ titulo }}{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons(titulo) %}
        {% if current_user.can_view('OFICINAS') %}
            {{ topbar.button('Oficinas', url_for('oficinas.list_active'), 'mdi:store') }}
        {% endif %}
        {% if current_user.can_admin('DOMICILIOS') %}
            {% if estatus == 'A' %}{{ topbar.button_list_inactive('Inactivos', url_for('domicilios.list_inactive')) }}{% endif %}
            {% if estatus == 'B' %}{{ topbar.button_list_active('Activos', url_for('domicilios.list_active')) }}{% endif %}
        {% endif %}
        {% if current_user.can_insert('DOMICILIOS') %}
            {{ topbar.button_new('Nuevo Domicilio', url_for('domicilios.new')) }}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call list.card() %}
        <!-- Filtros Domicilios -->
        <div class="row">
            <div class="col">
                <form class="row g-1 mb-3" id="filtradorForm" onsubmit="filtrosDomicilios.buscar(); return false;">
                    <div class="col-6">
                        <div class="form-floating">
                            <input id="filtroEdificio" type="text" class="form-control" aria-label="Edificio" style="text-transform: uppercase;">
                            <label for="filtroEdificio">Edificio</label>
                        </div>
                    </div>
                    <div class="col-6 text-end">
                        <button title="Buscar" class="btn btn-primary btn-lg" onclick="filtrosDomicilios.buscar(); return false;" id="button-buscar"><span class="iconify" data-icon="mdi:magnify"></span></button>
                        <button title="Limpiar" class="btn btn-warning btn-lg" type="reset" onclick="filtrosDomicilios.limpiar();" id="button-limpiar"><span class="iconify" data-icon="mdi:broom"></span></button>
                    </div>
                </form>
            </div>
        </div>
        <!-- DataTable Domicilios -->
        <table id="domicilios_datatable" class="table {% if estatus == 'B'%}table-dark{% endif %} display nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>Edificio</th>
                    <th>Estado</th>
                    <th>Municipio</th>
                    <th>Calle</th>
                    <th>No. Ext.</th>
                    <th>No. Int.</th>
                    <th>Colonia</th>
                    <th>C.P.</th>
                </tr>
            </thead>
        </table>
    {% endcall %}
{% endblock %}

{% block custom_javascript %}
    <script src="/static/js/datatables-constructor.js"></script>
    <script src="/static/js/datatables-filtros.js"></script>
    <script>
        // DataTable Domicilios
        const constructorDataTable = new ConfigDataTable( '{{ csrf_token() }}' );
        let configDataTable = constructorDataTable.config();
        configDataTable['ajax']['url'] = '/domicilios/datatable_json';
        configDataTable['ajax']['data'] = {{ filtros }};
        configDataTable['columns'] = [
            { data: "detalle" },
            { data: "estado" },
            { data: "municipio" },
            { data: "calle" },
            { data: "num_ext" },
            { data: "num_int" },
            { data: "colonia" },
            { data: "cp" }
        ];
        configDataTable['columnDefs'] = [
            {
                targets: 0, //detalle
                data: null,
                render: function(data, type, row, meta) {
                    return '<a href="' + data.url + '">' + data.edificio + '</a>';
                }
            },
            {
                targets: [1, 2], // estado, municipio
                data: null,
                render: function(data, type, row, meta) {
                    return data.length > 8 ? data.substring(0, 8) + '…' : data;
                }
            },
            {
                targets: [3, 6], // calle, colonia
                data: null,
                render: function(data, type, row, meta) {
                    return data.length > 16 ? data.substring(0, 16) + '…' : data;
                }
            }
        ];
        // Filtros Domicilios
        const filtrosDomicilios = new FiltrosDataTable('#domicilios_datatable', configDataTable);
        filtrosDomicilios.agregarInput('filtroEdificio', 'edificio');
        filtrosDomicilios.precargar();
    </script>
{% endblock %}

citas_admin/blueprints/domicilios/templates/domicilios/new.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Nuevo Domicilio{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Nuevo Domicilio') }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% call f.form_tag('domicilios.new', fid='domicilio_form') %}
            {% call f.form_group(form.distrito) %}{% endcall %}
            {% call f.form_group(form.edificio) %}{% endcall %}
            {% call f.form_group(form.estado) %}{% endcall %}
            {% call f.form_group(form.municipio) %}{% endcall %}
            {% call f.form_group(form.calle) %}{% endcall %}
            {% call f.form_group(form.num_ext) %}{% endcall %}
            {% call f.form_group(form.num_int) %}{% endcall %}
            {% call f.form_group(form.colonia) %}{% endcall %}
            {% call f.form_group(form.cp) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}