citas_admin/blueprints/pag_tramites_servicios/views.py
"""
Pag Tramites Servicios, vistas
"""

import json

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from citas_admin.blueprints.bitacoras.models import Bitacora
from citas_admin.blueprints.modulos.models import Modulo
from citas_admin.blueprints.pag_pagos.models import PagPago
from citas_admin.blueprints.pag_tramites_servicios.models import PagTramiteServicio
from citas_admin.blueprints.pag_tramites_servicios.forms import PagTramiteServicioForm
from citas_admin.blueprints.permisos.models import Permiso
from citas_admin.blueprints.usuarios.decorators import permission_required
from lib.datatables import get_datatable_parameters, output_datatable_json
from lib.safe_string import safe_clave, safe_message, safe_string

MODULO = "PAG TRAMITES SERVICIOS"

pag_tramites_servicios = Blueprint("pag_tramites_servicios", __name__, template_folder="templates")


@pag_tramites_servicios.before_request
@login_required
@permission_required(MODULO, Permiso.VER)
def before_request():
    """Permiso por defecto"""


@pag_tramites_servicios.route("/pag_tramites_servicios/datatable_json", methods=["GET", "POST"])
def datatable_json():
    """DataTable JSON para listado de PagTramiteServicio"""
    # Tomar parámetros de Datatables
    draw, start, rows_per_page = get_datatable_parameters()
    # Consultar
    consulta = PagTramiteServicio.query
    # Primero filtrar por columnas propias
    if "estatus" in request.form:
        consulta = consulta.filter_by(estatus=request.form["estatus"])
    else:
        consulta = consulta.filter_by(estatus="A")
    if "clave" in request.form:
        clave = safe_clave(request.form["clave"])
        if clave != "":
            consulta = consulta.filter(PagTramiteServicio.clave.contains(clave))
    if "descripcion" in request.form:
        descripcion = safe_string(request.form["descripcion"], save_enie=True)
        if descripcion != "":
            consulta = consulta.filter(PagTramiteServicio.descripcion.contains(descripcion))
    # Ordenar y paginar
    registros = consulta.order_by(PagTramiteServicio.clave).offset(start).limit(rows_per_page).all()
    total = consulta.count()
    # Elaborar datos para DataTable
    data = []
    for resultado in registros:
        data.append(
            {
                "detalle": {
                    "clave": resultado.clave,
                    "url": url_for("pag_tramites_servicios.detail", pag_tramite_servicio_id=resultado.id),
                },
                "descripcion": resultado.descripcion,
                "costo": resultado.costo,
                "url": resultado.url,
            }
        )
    # Entregar JSON
    return output_datatable_json(draw, total, data)


@pag_tramites_servicios.route("/pag_tramites_servicios")
def list_active():
    """Listado de PagTramiteServicio activos"""
    return render_template(
        "pag_tramites_servicios/list.jinja2",
        filtros=json.dumps({"estatus": "A"}),
        titulo="Trámites y Servicios",
        estatus="A",
    )


@pag_tramites_servicios.route("/pag_tramites_servicios/inactivos")
@permission_required(MODULO, Permiso.ADMINISTRAR)
def list_inactive():
    """Listado de PagTramiteServicio inactivos"""
    return render_template(
        "pag_tramites_servicios/list.jinja2",
        filtros=json.dumps({"estatus": "B"}),
        titulo="Trámites y Servicios inactivos",
        estatus="B",
    )


@pag_tramites_servicios.route("/pag_tramites_servicios/<int:pag_tramite_servicio_id>")
def detail(pag_tramite_servicio_id):
    """Detalle de un PagTramiteServicio"""
    pag_tramite_servicio = PagTramiteServicio.query.get_or_404(pag_tramite_servicio_id)
    return render_template(
        "pag_tramites_servicios/detail.jinja2",
        pag_tramite_servicio=pag_tramite_servicio,
        pag_pagos_estados=PagPago.ESTADOS,
    )


@pag_tramites_servicios.route("/pag_tramites_servicios/tablero")
def dashboard():
    """Tablero de PagTramiteServicio"""
    return render_template(
        "pag_tramites_servicios/dashboard.jinja2",
        pag_tramites_servicios=PagTramiteServicio.query.filter_by(estatus="A").order_by(PagTramiteServicio.clave).all(),
    )


@pag_tramites_servicios.route("/pag_tramites_servicios/nuevo", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.CREAR)
def new():
    """Nuevo PagTramiteServicio"""
    form = PagTramiteServicioForm()
    if form.validate_on_submit():
        es_valido = True
        # Validar que la clave no se repita
        clave = safe_clave(form.clave.data)
        if PagTramiteServicio.query.filter_by(clave=clave).first():
            flash("La clave ya está en uso. Debe de ser única.", "warning")
            es_valido = False
        # Si es válido, guardar
        if es_valido is True:
            pag_tramite_servicio = PagTramiteServicio(
                clave=clave,
                descripcion=safe_string(form.descripcion.data, save_enie=True),
                costo=form.costo.data,
                url=form.url.data,
            )
            pag_tramite_servicio.save()
            bitacora = Bitacora(
                modulo=Modulo.query.filter_by(nombre=MODULO).first(),
                usuario=current_user,
                descripcion=safe_message(f"Nuevo Trámite y Servicio {pag_tramite_servicio.clave}"),
                url=url_for("pag_tramites_servicios.detail", pag_tramite_servicio_id=pag_tramite_servicio.id),
            )
            bitacora.save()
            flash(bitacora.descripcion, "success")
            return redirect(bitacora.url)
    return render_template("pag_tramites_servicios/new.jinja2", form=form)


@pag_tramites_servicios.route("/pag_tramites_servicios/edicion/<int:pag_tramite_servicio_id>", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.MODIFICAR)
def edit(pag_tramite_servicio_id):
    """Editar PagTramiteServicio"""
    pag_tramite_servicio = PagTramiteServicio.query.get_or_404(pag_tramite_servicio_id)
    form = PagTramiteServicioForm()
    if form.validate_on_submit():
        es_valido = True
        # Si cambia la clave verificar que no este en uso
        clave = safe_clave(form.clave.data)
        if pag_tramite_servicio.clave != clave:
            pag_tramite_servicio_existente = PagTramiteServicio.query.filter_by(clave=clave).first()
            if pag_tramite_servicio_existente and pag_tramite_servicio_existente.id != pag_tramite_servicio.id:
                es_valido = False
                flash("La clave ya está en uso. Debe de ser única.", "warning")
        # Si es válido, actualizar
        if es_valido:
            pag_tramite_servicio.clave = clave
            pag_tramite_servicio.descripcion = safe_string(form.descripcion.data, save_enie=True)
            pag_tramite_servicio.costo = form.costo.data
            pag_tramite_servicio.url = form.url.data
            pag_tramite_servicio.save()
            bitacora = Bitacora(
                modulo=Modulo.query.filter_by(nombre=MODULO).first(),
                usuario=current_user,
                descripcion=safe_message(f"Editado Trámite y Servicio {pag_tramite_servicio.clave}"),
                url=url_for("pag_tramites_servicios.detail", pag_tramite_servicio_id=pag_tramite_servicio.id),
            )
            bitacora.save()
            flash(bitacora.descripcion, "success")
            return redirect(bitacora.url)
    form.clave.data = pag_tramite_servicio.clave
    form.descripcion.data = pag_tramite_servicio.descripcion
    form.costo.data = pag_tramite_servicio.costo
    form.url.data = pag_tramite_servicio.url
    return render_template(
        "pag_tramites_servicios/edit.jinja2",
        form=form,
        pag_tramite_servicio=pag_tramite_servicio,
    )


@pag_tramites_servicios.route("/pag_tramites_servicios/eliminar/<int:pag_tramite_servicio_id>")
@permission_required(MODULO, Permiso.ADMINISTRAR)
def delete(pag_tramite_servicio_id):
    """Eliminar PagTramiteServicio"""
    pag_tramite_servicio = PagTramiteServicio.query.get_or_404(pag_tramite_servicio_id)
    if pag_tramite_servicio.estatus == "A":
        pag_tramite_servicio.delete()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Eliminado Trámite y Servicio {pag_tramite_servicio.clave}"),
            url=url_for("pag_tramites_servicios.detail", pag_tramite_servicio_id=pag_tramite_servicio.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
    return redirect(url_for("pag_tramites_servicios.detail", pag_tramite_servicio_id=pag_tramite_servicio.id))


@pag_tramites_servicios.route("/pag_tramites_servicios/recuperar/<int:pag_tramite_servicio_id>")
@permission_required(MODULO, Permiso.ADMINISTRAR)
def recover(pag_tramite_servicio_id):
    """Recuperar PagTramiteServicio"""
    pag_tramite_servicio = PagTramiteServicio.query.get_or_404(pag_tramite_servicio_id)
    if pag_tramite_servicio.estatus == "B":
        pag_tramite_servicio.recover()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Recuperado Trámite y Servicio {pag_tramite_servicio.clave}"),
            url=url_for("pag_tramites_servicios.detail", pag_tramite_servicio_id=pag_tramite_servicio.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
    return redirect(url_for("pag_tramites_servicios.detail", pag_tramite_servicio_id=pag_tramite_servicio.id))

citas_admin/blueprints/pag_tramites_servicios/templates/pag_tramites_servicios/dashboard.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/card.jinja2' as card %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Tablero de Trámites y Servicios{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons('Tablero de Trámites y Servicios') %}
        {{ topbar.button_list_active('Listado', url_for('pag_tramites_servicios.list_active')) }}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call card.container_row() %}
        <!-- Bucle por cada trámite o servicio -->
        {% for pag_tramite_servicio in pag_tramites_servicios %}
            {% call card.col_md(4) %}
                {% call card.card(pag_tramite_servicio.clave) %}
                    {% call card.card_body(button_text='Generar reporte') %}
                        {% call card.list_unstyled() %}
                            <li>{{ pag_tramite_servicio.descripcion }}</li>
                            <li>Hay 000 registros pagados y/o entregados.</li>
                        {% endcall %}
                    {% endcall %}
                {% endcall %}
            {% endcall %}
        {% endfor %}
    {% endcall %}
{% endblock %}

citas_admin/blueprints/pag_tramites_servicios/templates/pag_tramites_servicios/detail.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/detail.jinja2' as detail %}
{% import 'macros/modals.jinja2' as modals %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Trámite y Servicio {{ pag_tramite_servicio.clave }}{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons('Trámite y Servicio ' + pag_tramite_servicio.clave) %}
        {{ topbar.button_previous('Trámites y Servicios', url_for('pag_tramites_servicios.list_active')) }}
        {% if current_user.can_edit('PAG TRAMITES SERVICIOS') %}
            {{ topbar.button_edit('Editar', url_for('pag_tramites_servicios.edit', pag_tramite_servicio_id=pag_tramite_servicio.id)) }}
        {% endif %}
        {% if current_user.can_admin('PAG TRAMITES SERVICIOS') %}
            {% if pag_tramite_servicio.estatus == 'A' %}{{ topbar.button_delete('Eliminar', url_for('pag_tramites_servicios.delete', pag_tramite_servicio_id=pag_tramite_servicio.id)) }}{% endif %}
            {% if pag_tramite_servicio.estatus == 'B' %}{{ topbar.button_recover('Recuperar', url_for('pag_tramites_servicios.recover', pag_tramite_servicio_id=pag_tramite_servicio.id)) }}{% endif %}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call detail.card(estatus=pag_tramite_servicio.estatus) %}
        {{ detail.label_value_big('Clave', pag_tramite_servicio.clave) }}
        {{ detail.label_value('Descripción', pag_tramite_servicio.descripcion) }}
        {{ detail.label_value('Costo', '$ ' + pag_tramite_servicio.costo | string) }}
        {{ detail.label_value('URL', pag_tramite_servicio.url, pag_tramite_servicio.url) }}
    {% endcall %}
    {% if current_user.can_view('PAG PAGOS') %}
        {% call detail.card('Pagos') %}
            <!-- Filtros PagPagos -->
            <div class="row">
                <div class="col">
                    <form class="row g-1 mb-3" id="filtradorForm" onsubmit="filtrosPagPagos.buscar(); return false;">
                        <div class="col-4">
                            <div class="form-floating">
                                <input id="filtroPagPagoCitClienteEmail" type="text" class="form-control" aria-label="e-mail">
                                <label for="filtroPagPagoCitClienteEmail">e-mail</label>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-floating">
                                <input id="filtroPagPagoCitClienteNombres" type="text" class="form-control" aria-label="Nombres" style="text-transform: uppercase">
                                <label for="filtroPagPagoCitClienteNombres">Nombres</label>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-floating">
                                <input id="filtroPagPagoCitClientePrimerApellido" type="text" class="form-control" aria-label="Primer Apellido" style="text-transform: uppercase">
                                <label for="filtroPagPagoCitClientePrimerApellido">Primer Apellido</label>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="form-floating">
                                <input id="filtroPagPagoId" type="text" class="form-control" aria-label="ID">
                                <label for="filtroPagPagoId">ID</label>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="form-floating">
                                <input id="filtroPagPagoFechaDesde" type="date" class="form-control" aria-label="Desde">
                                <label for="filtroPagPagoFechaDesde">Desde</label>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="form-floating">
                                <input id="filtroPagPagoFechaHasta" type="date" class="form-control" aria-label="Hasta">
                                <label for="filtroPagPagoFechaHasta">Hasta</label>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="form-floating">
                                <select id="filtroPagPagoEstado" class="form-select" aria-label="Estado">
                                    <option selected value="">Todos</option>
                                    {% for estado in pag_pagos_estados %}
                                    <option value="{{estado}}">{{estado}}</option>
                                    {% endfor %}
                                </select>
                                <label for="filtroPagPagoEstado">Estado</label>
                            </div>
                        </div>
                        <div class="col-4 text-end">
                            <button title="Buscar" class="btn btn-primary btn-lg" onclick="filtrosPagPagos.buscar(); return false;" id="button-buscar"><span class="iconify" data-icon="mdi:magnify"></span></button>
                            <button title="Limpiar" class="btn btn-warning btn-lg" type="reset" onclick="filtrosPagPagos.limpiar();" id="button-limpiar"><span class="iconify" data-icon="mdi:broom"></span></button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- DataTable PagPagos -->
            <table id="pag_pagos_datatable" class="table display nowrap" style="width:100%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Fecha</th>
                        <th>Nombre</th>
                        <th>Email</th>
                        <th>Cantidad</th>
                        <th>Distrito</th>
                        <th>Autoridad</th>
                        <th>Folio</th>
                        <th>Total</th>
                        <th>Estado</th>
                    </tr>
                </thead>
            </table>
        {% endcall %}
    {% endif %}
{% endblock %}

{% block custom_javascript %}
    {% if current_user.can_admin('PAG TRAMITES SERVICIOS') %}
        {% if pag_tramite_servicio.estatus == 'A' %}{{ modals.custom_javascript_delete('Eliminar', '¿Eliminar a ' + pag_tramite_servicio.clave + '?') }}{% endif %}
        {% if pag_tramite_servicio.estatus == 'B' %}{{ modals.custom_javascript_recover('Recuperar', '¿Recuperar a ' + pag_tramite_servicio.clave + '?') }}{% endif %}
    {% endif %}
    <script src="/static/js/datatables-constructor.js"></script>
    <script src="/static/js/datatables-filtros.js"></script>
    {% if current_user.can_view('PAG PAGOS') %}
        <script>
            // DataTable PagPagos
            const constructorDataTable = new ConfigDataTable( '{{ csrf_token() }}' );
            let configDTPagPagos = constructorDataTable.config();
            configDTPagPagos['ajax']['url'] = '/pag_pagos/datatable_json';
            configDTPagPagos['ajax']['data'] = { 'estatus': "A", 'pag_tramite_servicio_id': {{ pag_tramite_servicio.id }} };
            configDTPagPagos['columns'] = [
                { data: 'detalle' },
                { data: 'fecha' },
                { data: 'cit_cliente' },
                { data: 'email' },
                { data: 'cantidad', className: "text-end" },
                { data: 'distrito' },
                { data: 'autoridad' },
                { data: 'folio' },
                { data: 'total', className: "text-end" },
                { data: 'estado' }
            ];
            configDTPagPagos['columnDefs'] = [
                {
                    targets: 0, // detalle
                    data: null,
                    render: function(data, type, row, meta) {
                        return '<a href="' + data.url + '">' + data.id + '</a>';
                    }
                },
                {
                    targets: 1, // fecha
                    type: 'date',
                    render: function (data, type, row) {
                        return moment.utc(data).local().format('YYYY-MM-DD HH:mm');
                    }
                },
                {
                    targets: 2, // cit_cliente
                    data: null,
                    render: function(data, type, row, meta) {
                        let texto = data.nombre;
                        if (texto.length > 16 ) {
                            texto = data.nombre.substring(0, 16) + '…'
                        }
                        if (data.url === '') {
                            return '<span title="' + data.nombre + '">' + texto + '</span>';
                        }
                        return '<a href="' + data.url + '"><span title="' + data.nombre + '">' + texto + '</span></a>';
                    }
                },
                {
                    targets: 3, // email
                    data: null,
                    render: function(data, type, row, meta) {
                        if (data.length < 16 ) {
                            return '<a href="mailto:' + data + '">' + data + '</a>';
                        }
                        return '<a href="mailto:' + data + '"><span title="' + data + '">' + data.substring(0, 16) + '…' + '</span></a>';
                    }
                },
                {
                    targets: [5, 6], // distrito, autoridad
                    data: null,
                    render: function(data, type, row, meta) {
                        if (data.url === '') {
                            return data.nombre_corto;
                        }
                        return '<a href="' + data.url + '"><span title="' + data.nombre_corto + '">' + data.clave + '</span></a>';
                    }
                },
                {
                    targets: 8, // total
                    data: null,
                    render: function(data, type, row, meta) {
                        return '$ ' + data;
                    }
                },
                {
                    targets: 9, // Estado
                    data: null,
                    render: function(data, type, row, meta) {
                        let color = "black";
                        switch (data)    {
                            case "SOLICITADO": font_color = "#7d6608"; bg_class = "bg-warning text-dark"; break;
                            case "PAGADO":     font_color = "#0b5345"; bg_class = "bg-success"; break;
                            case "ENTREGADO":  font_color = "#c7f6ff"; bg_class = "bg-info"; break;
                            case "CANCELADO":  font_color = "#e53935"; bg_class = "bg-secondary"; break;
                            case "FALLIDO":    font_color = "#e53935"; bg_class = "bg-danger"; break;
                        }
                        return '<span class="badge rounded-pill ' + bg_class + ' px-3">' + data + '</span>';
                    }
                }
            ];
            // DataTable estilos en las filas segun estado
            configDataTable['createdRow'] = function(row, data, dataIndex) {
                switch (data.estado) {
                    case "SOLICITADO": $(row).addClass('table-warning'); break;
                    case "PAGADO":     $(row).addClass('table-success'); break;
                    case "ENTREGADO":  $(row).addClass('table-info'); break;
                    case "CANCELADO":  $(row).addClass('table-secondary'); break;
                    case "FALLIDO":    $(row).addClass('table-danger'); break;
                }
            };
            // Filtros PagPagos
            const filtrosPagPagos = new FiltrosDataTable('#pag_pagos_datatable', configDTPagPagos);
            filtrosPagPagos.agregarInput('filtroPagPagoId', 'id');
            filtrosPagPagos.agregarInput('filtroPagPagoFechaDesde', 'fecha_desde');
            filtrosPagPagos.agregarInput('filtroPagPagoFechaHasta', 'fecha_hasta');
            filtrosPagPagos.agregarInput('filtroPagPagoCitClienteEmail', 'cit_cliente_email');
            filtrosPagPagos.agregarInput('filtroPagPagoCitClienteNombres', 'cit_cliente_nombres');
            filtrosPagPagos.agregarInput('filtroPagPagoCitClientePrimerApellido', 'cit_cliente_primer_apellido');
            filtrosPagPagos.agregarInput('filtroPagPagoEstado', 'estado');
            filtrosPagPagos.precargar();
        </script>
    {% endif %}
{% endblock %}

citas_admin/blueprints/pag_tramites_servicios/templates/pag_tramites_servicios/edit.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Editar Trámite y Servicio {{ pag_tramite_servicio.clave }}{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Editar Trámite y Servicio ' + pag_tramite_servicio.clave) }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% set form_kwargs = {'pag_tramite_servicio_id': pag_tramite_servicio.id} %}
        {% call f.form_tag('pag_tramites_servicios.edit', fid='pag_tramite_servicio_form', **form_kwargs) %}
            {% call f.form_group(form.clave) %}{% endcall %}
            {% call f.form_group(form.descripcion) %}{% endcall %}
            {% call f.form_group(form.costo) %}{% endcall %}
            {% call f.form_group(form.url) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}

citas_admin/blueprints/pag_tramites_servicios/templates/pag_tramites_servicios/list.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/list.jinja2' as list %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}{{ titulo }}{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons(titulo) %}
        {{ topbar.button_dashboard('Tablero', url_for('pag_tramites_servicios.dashboard')) }}
        {% if current_user.can_admin('PAG TRAMITES SERVICIOS') %}
            {% if estatus == 'A' %}{{ topbar.button_list_inactive('Inactivos', url_for('pag_tramites_servicios.list_inactive')) }}{% endif %}
            {% if estatus == 'B' %}{{ topbar.button_list_active('Activos', url_for('pag_tramites_servicios.list_active')) }}{% endif %}
        {% endif %}
        {% if current_user.can_insert('PAG TRAMITES SERVICIOS') %}
            {{ topbar.button_new('Nuevo Trámite y Servicio', url_for('pag_tramites_servicios.new')) }}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call list.card() %}
        <!-- Filtros PagTramitesServicios -->
        <div class="row">
            <div class="col">
                <form class="row g-1 mb-3" id="filtradorForm" onsubmit="filtrosPagTramitesServicios.buscar(); return false;">
                    <div class="col-4">
                        <div class="form-floating">
                            <input id="filtroClave" type="text" class="form-control" aria-label="Clave" style="text-transform: uppercase;">
                            <label for="filtroClave">Clave</label>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-floating">
                            <input id="filtroDescripcion" type="text" class="form-control" aria-label="Descripción" style="text-transform: uppercase;">
                            <label for="filtroDescripcion">Descripción</label>
                        </div>
                    </div>
                    <div class="col-2 text-end">
                        <button title="Buscar" class="btn btn-primary btn-lg" onclick="filtrosPagTramitesServicios.buscar(); return false;" id="button-buscar"><span class="iconify" data-icon="mdi:magnify"></span></button>
                        <button title="Limpiar" class="btn btn-warning btn-lg" type="reset" onclick="filtrosPagTramitesServicios.limpiar();" id="button-limpiar"><span class="iconify" data-icon="mdi:broom"></span></button>
                    </div>
                </form>
            </div>
        </div>
        <!-- DataTable PagTramitesServicios -->
        <table id="pag_tramites_servicios_datatable" class="table {% if estatus == 'B'%}table-dark{% endif %} display nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>Clave</th>
                    <th>Descripción</th>
                    <th>Costo</th>
                    <th>URL</th>
                </tr>
            </thead>
        </table>
    {% endcall %}
{% endblock %}

{% block custom_javascript %}
    <script src="/static/js/datatables-constructor.js"></script>
    <script src="/static/js/datatables-filtros.js"></script>
    <script>
        // DataTable PagTramitesServicios
        const constructorDataTable = new ConfigDataTable( '{{ csrf_token() }}' );
        let configDataTable = constructorDataTable.config();
        configDataTable['ajax']['url'] = '/pag_tramites_servicios/datatable_json';
        configDataTable['ajax']['data'] = {{ filtros }};
        configDataTable['columns'] = [
            { data: 'detalle' },
            { data: 'descripcion' },
            { data: 'costo', className: "text-end" },
            { data: 'url' }
        ];
        configDataTable['columnDefs'] = [
            {
                targets: 0, // detalle
                data: null,
                render: function(data, type, row, meta) {
                    return '<a href="' + data.url + '">' + data.clave + '</a>';
                }
            },
            {
                targets: 1, // descripcion
                data: null,
                render: function(data, type, row, meta) {
                    return data.length > 48 ? data.substring(0, 48) + '…' : data;
                }
            },
            {
                targets: 2, // costo
                data: null,
                render: function(data, type, row, meta) {
                    return '$ ' + data;
                }
            },
            {
                targets: 3, // URL
                data: null,
                render: function(data, type, row, meta) {
                    if (data !== '') {
                        texto = data.length > 48 ? '…' + data.slice(-48) : data;
                        return data === '' ? '' : '<a href="' + data + '" target="_blank">' + texto + '<span class="iconify" data-icon="mdi:open-in-new"></span></a>';
                    }
                    return '';
                }
            }
        ];
        // Filtros PagTramitesServicios
        const filtrosPagTramitesServicios = new FiltrosDataTable('#pag_tramites_servicios_datatable', configDataTable);
        filtrosPagTramitesServicios.agregarInput('filtroClave', 'clave');
        filtrosPagTramitesServicios.agregarInput('filtroDescripcion', 'descripcion');
        filtrosPagTramitesServicios.precargar();
    </script>
{% endblock %}

citas_admin/blueprints/pag_tramites_servicios/templates/pag_tramites_servicios/new.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Nuevo Trámite y Servicio{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Nuevo Trámite y Servicio') }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% call f.form_tag('pag_tramites_servicios.new', fid='pag_tramite_servicio_form') %}
            {% call f.form_group(form.clave) %}{% endcall %}
            {% call f.form_group(form.descripcion) %}{% endcall %}
            {% call f.form_group(form.costo) %}{% endcall %}
            {% call f.form_group(form.url) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}